### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [ConstantinoSchillebeeckx/tacocat-keyboard#1]
- [x] finalize [key layout](http://www.keyboard-layout-editor.com/#/gists/eb286e554d9060f3198149826c6e62ab) -> [final](http://www.keyboard-layout-editor.com/#/gists/307251af9e96b164b4af86ab172ea8ab)
- [x] PCB
  - [x] ensure symmetric PCB layout works
  - [x] design finalized PCB
- [ ] custom TRRS and USB cables
- [ ] case
  - [ ] design case (CAD)
  - [x] figure out how to mount pcb to case
  - [ ] plate CAM & fab (1.5mm or 0.059in thick)
  - [ ] figure out how to interface with tenting stands
- [ ] figure out how to mill wood keycaps
  - [x] test fit of new wall thickness keys
  - [ ] figure out laser alignment for lettering
  - [ ] art resin?
  - [x] finalize CAM
- [ ] software
